name: Rust

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".editorconfig"
      - ".gitignore"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".editorconfig"
      - ".gitignore"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache build
        uses: Swatinem/rust-cache@v2
      - name: Add components
        run: |
          rustup component add rustfmt
          rustup component add clippy
          rustup component add llvm-tools
      - name: Install target
        run: rustup target install thumbv6m-none-eabi
      - name: Install other tools
        run: cargo install flip-link
      - name: Build
        run: cargo build --verbose
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy -- -D warnings
